@base_url = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1MDk4MTk1NSwianRpIjoiZmY1YjM5NTgtMmVlNC00ZWJmLTg4NGEtMzgyMjU3YzA2NDY3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjQiLCJuYmYiOjE3NTA5ODE5NTUsImNzcmYiOiIxMjZiN2VkMy0xMDRhLTQzZWQtYjBhZi1jZTQzZjBkM2QxNDQiLCJleHAiOjE3NTA5ODI4NTV9.QzB5U9F-cV34XFY8VN-t-pHnGfdKHMoNurkZtN8fyLE

### REGISTRAR USUÁRIO
POST {{base_url}}/api/register
Content-Type: application/json

{
  "email": "claudia@email.com",
  "password": "123456"
}

### LOGIN E COPIE O TOKEN
POST {{base_url}}/api/login
Content-Type: application/json

{
  "email": "teste@example.com",
  "password": "123456"
}

### BUSCA NO GOOGLE BOOKS
GET {{base_url}}/api/user/books/search?query=grandes+esperancas
Authorization: Bearer {{token}}
Content-Type: application/json

### ADICIONAR REVIEW
# Substitua "omH0DwAAQBAJ" por outro google_id se quiser
POST {{base_url}}/api/user/books/omH0DwAAQBAJ
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rating": 5,
  "comment": "Um clássico!",
  "status": "lido"
}

### ATUALIZAR REVIEW
PUT {{base_url}}/api/user/books/omH0DwAAQBAJ
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rating": 4,
  "comment": "Na releitura, gostei ainda mais",
  "status": "lendo"
}

### DELETAR REVIEW
DELETE {{base_url}}/api/user/books/omH0DwAAQBAJ
Authorization: Bearer {{token}}

### ATUALIZAR STATUS DO LIVRO
PATCH {{base_url}}/api/user/books/omH0DwAAQBAJ/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "lido"
}
